//! Generated from `spec-refs/{KerML,SysML}.xmi` (normative metamodel
//! 20250201) by `tools/derived_census.py` — do not edit.
//!
//! Kind-filtered compositions among the derived properties: `name =
//! base->selectByKind(kind)` per the OCL derivation rules, and the
//! rule-less `*Definition` back-references, which the normative
//! documentation defines as the usage's `definition`s of the
//! property's declared type. `single` marks an upper bound of 1 (the
//! first match, else null). A composition is computable exactly when
//! its base is.

/// `(name, base, kind, single)`, sorted by name.
pub(crate) static COMPOSITIONS: &[(&str, &str, &str, bool)] = &[
    ("action", "usage", "ActionUsage", false),
    ("actionDefinition", "definition", "Behavior", false),
    ("allocation", "usage", "AllocationUsage", false),
    (
        "allocationDefinition",
        "definition",
        "AllocationDefinition",
        false,
    ),
    (
        "analysisCaseDefinition",
        "definition",
        "AnalysisCaseDefinition",
        true,
    ),
    ("attributeDefinition", "definition", "DataType", false),
    ("behavior", "type", "Behavior", false),
    ("calculation", "action", "CalculationUsage", false),
    ("calculationDefinition", "definition", "Function", true),
    ("caseDefinition", "definition", "CaseDefinition", true),
    ("concernDefinition", "definition", "ConcernDefinition", true),
    (
        "connectionDefinition",
        "definition",
        "AssociationStructure",
        false,
    ),
    ("constraintDefinition", "definition", "Predicate", true),
    ("directedUsage", "directedFeature", "Usage", false),
    ("documentation", "ownedElement", "Documentation", false),
    (
        "enumerationDefinition",
        "definition",
        "EnumerationDefinition",
        true,
    ),
    ("flowDefinition", "definition", "Interaction", false),
    ("flowEnd", "connectorEnd", "FlowEnd", false),
    (
        "interfaceDefinition",
        "definition",
        "InterfaceDefinition",
        false,
    ),
    ("itemDefinition", "occurrenceDefinition", "Structure", false),
    ("metadataDefinition", "definition", "Metaclass", true),
    ("nestedAction", "nestedUsage", "ActionUsage", false),
    ("nestedAllocation", "nestedUsage", "AllocationUsage", false),
    (
        "nestedAnalysisCase",
        "nestedUsage",
        "AnalysisCaseUsage",
        false,
    ),
    ("nestedAttribute", "nestedUsage", "AttributeUsage", false),
    (
        "nestedCalculation",
        "nestedUsage",
        "CalculationUsage",
        false,
    ),
    ("nestedCase", "nestedUsage", "CaseUsage", false),
    ("nestedConcern", "nestedUsage", "ConcernUsage", false),
    ("nestedConnection", "nestedUsage", "ConnectorAsUsage", false),
    ("nestedConstraint", "nestedUsage", "ConstraintUsage", false),
    (
        "nestedEnumeration",
        "nestedUsage",
        "EnumerationUsage",
        false,
    ),
    ("nestedFlow", "nestedUsage", "FlowConnectionUsage", false),
    ("nestedInterface", "nestedUsage", "ReferenceUsage", false),
    ("nestedItem", "nestedUsage", "ItemUsage", false),
    ("nestedMetadata", "nestedUsage", "MetadataUsage", false),
    ("nestedOccurrence", "nestedUsage", "OccurrenceUsage", false),
    ("nestedPart", "nestedUsage", "PartUsage", false),
    ("nestedPort", "nestedUsage", "PortUsage", false),
    ("nestedReference", "nestedUsage", "ReferenceUsage", false),
    ("nestedRendering", "nestedUsage", "RenderingUsage", false),
    (
        "nestedRequirement",
        "nestedUsage",
        "RequirementUsage",
        false,
    ),
    ("nestedState", "nestedUsage", "StateUsage", false),
    ("nestedTransition", "nestedUsage", "TransitionUsage", false),
    ("nestedUsage", "ownedFeature", "Usage", false),
    ("nestedUseCase", "nestedUsage", "UseCaseUsage", false),
    (
        "nestedVerificationCase",
        "nestedUsage",
        "VerificationCaseUsage",
        false,
    ),
    ("nestedView", "nestedUsage", "ViewUsage", false),
    ("nestedViewpoint", "nestedUsage", "ViewpointUsage", false),
    ("occurrenceDefinition", "definition", "Class", false),
    ("ownedAction", "ownedUsage", "ActionUsage", false),
    ("ownedAllocation", "ownedUsage", "AllocationUsage", false),
    (
        "ownedAnalysisCase",
        "ownedUsage",
        "AnalysisCaseUsage",
        false,
    ),
    ("ownedAttribute", "ownedUsage", "AttributeUsage", false),
    ("ownedCalculation", "ownedUsage", "CalculationUsage", false),
    ("ownedCase", "ownedUsage", "CaseUsage", false),
    ("ownedConcern", "ownedUsage", "ConcernUsage", false),
    ("ownedConnection", "ownedUsage", "ConnectorAsUsage", false),
    ("ownedConstraint", "ownedUsage", "ConstraintUsage", false),
    (
        "ownedDifferencing",
        "ownedRelationship",
        "Differencing",
        false,
    ),
    ("ownedDisjoining", "ownedRelationship", "Disjoining", false),
    ("ownedEnumeration", "ownedUsage", "EnumerationUsage", false),
    (
        "ownedFeatureChaining",
        "ownedRelationship",
        "FeatureChaining",
        false,
    ),
    (
        "ownedFeatureMembership",
        "ownedRelationship",
        "FeatureMembership",
        false,
    ),
    ("ownedFlow", "ownedUsage", "FlowConnectionUsage", false),
    ("ownedImport", "ownedRelationship", "Import", false),
    ("ownedInterface", "ownedUsage", "ReferenceUsage", false),
    (
        "ownedIntersecting",
        "ownedRelationship",
        "Intersecting",
        false,
    ),
    ("ownedItem", "ownedUsage", "ItemUsage", false),
    ("ownedMembership", "ownedRelationship", "Membership", false),
    ("ownedMetadata", "ownedUsage", "MetadataUsage", false),
    ("ownedOccurrence", "ownedUsage", "OccurrenceUsage", false),
    ("ownedPart", "ownedUsage", "PartUsage", false),
    ("ownedPort", "ownedUsage", "PortUsage", false),
    (
        "ownedRedefinition",
        "ownedSubsetting",
        "Redefinition",
        false,
    ),
    ("ownedReference", "ownedUsage", "ReferenceUsage", false),
    ("ownedRendering", "ownedUsage", "RenderingUsage", false),
    ("ownedRequirement", "ownedUsage", "RequirementUsage", false),
    ("ownedState", "ownedUsage", "StateUsage", false),
    (
        "ownedSubclassification",
        "ownedSpecialization",
        "Subclassification",
        false,
    ),
    (
        "ownedSubsetting",
        "ownedSpecialization",
        "Subsetting",
        false,
    ),
    ("ownedTransition", "ownedUsage", "TransitionUsage", false),
    ("ownedTyping", "ownedSpecialization", "FeatureTyping", false),
    ("ownedUnioning", "ownedRelationship", "Unioning", false),
    ("ownedUsage", "ownedFeature", "Usage", false),
    ("ownedUseCase", "ownedUsage", "UseCaseUsage", false),
    (
        "ownedVerificationCase",
        "ownedUsage",
        "VerificationCaseUsage",
        false,
    ),
    ("ownedView", "ownedUsage", "ViewUsage", false),
    ("ownedViewpoint", "ownedUsage", "ViewpointUsage", false),
    ("partDefinition", "itemDefinition", "PartDefinition", false),
    ("portDefinition", "definition", "PortDefinition", false),
    ("rendering", "usage", "RenderingUsage", false),
    (
        "renderingDefinition",
        "definition",
        "RenderingDefinition",
        true,
    ),
    (
        "requirementDefinition",
        "definition",
        "RequirementDefinition",
        true,
    ),
    ("state", "action", "StateUsage", false),
    ("stateDefinition", "definition", "Behavior", false),
    ("step", "feature", "Step", false),
    (
        "textualRepresentation",
        "ownedElement",
        "TextualRepresentation",
        false,
    ),
    ("usage", "feature", "Usage", false),
    ("useCaseDefinition", "definition", "UseCaseDefinition", true),
    (
        "variantMembership",
        "ownedMembership",
        "VariantMembership",
        false,
    ),
    (
        "verificationCaseDefinition",
        "definition",
        "VerificationCaseDefinition",
        true,
    ),
    ("view", "usage", "ViewUsage", false),
    ("viewDefinition", "definition", "ViewDefinition", true),
    (
        "viewpointDefinition",
        "definition",
        "ViewpointDefinition",
        true,
    ),
];
