//! Generated by `tools/operation_catalog.py` from the normative 20250201 XMI.
//! Declaration metadata only; no executable support is implied.

#[derive(Debug)]
pub struct ParameterSpec {
    pub id: &'static str,
    pub name: &'static str,
    pub target: &'static str,
    /// The explicit XMI direction, or None if omitted. No return role is inferred.
    pub direction: Option<&'static str>,
    pub lower: usize,
    pub upper: Option<usize>,
    pub ordered: bool,
    pub unique: bool,
}

#[derive(Debug)]
pub struct OperationSpec {
    pub id: &'static str,
    pub declaring_metaclass: &'static str,
    pub name: &'static str,
    pub redefines: &'static [&'static str],
    /// Source declaration order, including unnamed parameters.
    pub parameters: &'static [ParameterSpec],
}

#[rustfmt::skip]
pub static OPERATIONS: &[OperationSpec] = &[
    OperationSpec { id: "Core-Features-Feature-allRedefinedFeatures_", declaring_metaclass: "Feature", name: "allRedefinedFeatures", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-allRedefinedFeatures_-", name: "", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-asCartesianProduct_", declaring_metaclass: "Feature", name: "asCartesianProduct", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-asCartesianProduct_-", name: "", target: "Type", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Core-Features-Feature-canAccess_Feature", declaring_metaclass: "Feature", name: "canAccess", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-canAccess_Feature-feature", name: "feature", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-canAccess_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-directionFor_Type", declaring_metaclass: "Feature", name: "directionFor", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-directionFor_Type-type", name: "type", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-directionFor_Type-", name: "", target: "FeatureDirectionKind", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-effectiveName_", declaring_metaclass: "Feature", name: "effectiveName", redefines: &["Root-Elements-Element-effectiveName_"], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-effectiveName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-effectiveShortName_", declaring_metaclass: "Feature", name: "effectiveShortName", redefines: &["Root-Elements-Element-effectiveShortName_"], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-effectiveShortName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-isCartesianProduct_", declaring_metaclass: "Feature", name: "isCartesianProduct", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-isCartesianProduct_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-isCompatibleWith_Type", declaring_metaclass: "Feature", name: "isCompatibleWith", redefines: &["Core-Types-Type-isCompatibleWith_Type"], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-isCompatibleWith_Type-otherType", name: "otherType", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-isFeaturedWithin_Type", declaring_metaclass: "Feature", name: "isFeaturedWithin", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-isFeaturedWithin_Type-type", name: "type", target: "Type", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-isFeaturedWithin_Type-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-isFeaturingType_Type", declaring_metaclass: "Feature", name: "isFeaturingType", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-isFeaturingType_Type-type", name: "type", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-isFeaturingType_Type-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-isOwnedCrossFeature_", declaring_metaclass: "Feature", name: "isOwnedCrossFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-isOwnedCrossFeature_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-namingFeature_", declaring_metaclass: "Feature", name: "namingFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-namingFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-ownedCrossFeature_", declaring_metaclass: "Feature", name: "ownedCrossFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-ownedCrossFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-redefinesFromLibrary_String", declaring_metaclass: "Feature", name: "redefinesFromLibrary", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-redefinesFromLibrary_String-libraryFeatureName", name: "libraryFeatureName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-redefinesFromLibrary_String-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-redefines_Feature", declaring_metaclass: "Feature", name: "redefines", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-redefines_Feature-redefinedFeature", name: "redefinedFeature", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-redefines_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-subsetsChain_Feature_Feature", declaring_metaclass: "Feature", name: "subsetsChain", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-subsetsChain_Feature_Feature-first", name: "first", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-subsetsChain_Feature_Feature-second", name: "second", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-subsetsChain_Feature_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-supertypes_Boolean", declaring_metaclass: "Feature", name: "supertypes", redefines: &["Core-Types-Type-supertypes_Boolean"], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-supertypes_Boolean-excludeImplied", name: "excludeImplied", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Features-Feature-supertypes_Boolean-", name: "", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Features-Feature-typingFeatures_", declaring_metaclass: "Feature", name: "typingFeatures", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Features-Feature-typingFeatures_-", name: "", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-allRedefinedFeaturesOf_Membership", declaring_metaclass: "Type", name: "allRedefinedFeaturesOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-allRedefinedFeaturesOf_Membership-membership", name: "membership", target: "Membership", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-allRedefinedFeaturesOf_Membership-", name: "", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-allSupertypes_", declaring_metaclass: "Type", name: "allSupertypes", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-allSupertypes_-result", name: "result", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-directionOfExcluding_Feature_Type", declaring_metaclass: "Type", name: "directionOfExcluding", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-directionOfExcluding_Feature_Type-feature", name: "feature", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-directionOfExcluding_Feature_Type-excluded", name: "excluded", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-directionOfExcluding_Feature_Type-", name: "", target: "FeatureDirectionKind", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-directionOf_Feature", declaring_metaclass: "Type", name: "directionOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-directionOf_Feature-feature", name: "feature", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-directionOf_Feature-", name: "", target: "FeatureDirectionKind", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-inheritableMemberships_Namespace_Type_Boolean", declaring_metaclass: "Type", name: "inheritableMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-inheritableMemberships_Namespace_Type_Boolean-excludedNamespaces", name: "excludedNamespaces", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritableMemberships_Namespace_Type_Boolean-excludedTypes", name: "excludedTypes", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritableMemberships_Namespace_Type_Boolean-excludeImplied", name: "excludeImplied", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritableMemberships_Namespace_Type_Boolean-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-inheritedMemberships_Namespace_Type_Boolean", declaring_metaclass: "Type", name: "inheritedMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-inheritedMemberships_Namespace_Type_Boolean-excludedNamespaces", name: "excludedNamespaces", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritedMemberships_Namespace_Type_Boolean-excludedTypes", name: "excludedTypes", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritedMemberships_Namespace_Type_Boolean-excludeImplied", name: "excludeImplied", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-inheritedMemberships_Namespace_Type_Boolean-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-isCompatibleWith_Type", declaring_metaclass: "Type", name: "isCompatibleWith", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-isCompatibleWith_Type-otherType", name: "otherType", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-multiplicities_", declaring_metaclass: "Type", name: "multiplicities", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-multiplicities_-", name: "", target: "Multiplicity", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-nonPrivateMemberships_Namespace_Type_Boolean", declaring_metaclass: "Type", name: "nonPrivateMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-nonPrivateMemberships_Namespace_Type_Boolean-excludedNamespaces", name: "excludedNamespaces", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-nonPrivateMemberships_Namespace_Type_Boolean-excludedTypes", name: "excludedTypes", target: "Type", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-nonPrivateMemberships_Namespace_Type_Boolean-excludeImplied", name: "excludeImplied", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-nonPrivateMemberships_Namespace_Type_Boolean-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-removeRedefinedFeatures_Membership", declaring_metaclass: "Type", name: "removeRedefinedFeatures", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-removeRedefinedFeatures_Membership-memberships", name: "memberships", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
        ParameterSpec { id: "Core-Types-Type-removeRedefinedFeatures_Membership-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-specializesFromLibrary_String", declaring_metaclass: "Type", name: "specializesFromLibrary", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-specializesFromLibrary_String-libraryTypeName", name: "libraryTypeName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-specializesFromLibrary_String-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-specializes_Type", declaring_metaclass: "Type", name: "specializes", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-specializes_Type-supertype", name: "supertype", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-specializes_Type-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-supertypes_Boolean", declaring_metaclass: "Type", name: "supertypes", redefines: &[], parameters: &[
        ParameterSpec { id: "Core-Types-Type-supertypes_Boolean-excludeImplied", name: "excludeImplied", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-supertypes_Boolean-", name: "", target: "Type", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Core-Types-Type-visibleMemberships_Namespace_Boolean_Boolean", declaring_metaclass: "Type", name: "visibleMemberships", redefines: &["Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean"], parameters: &[
        ParameterSpec { id: "Core-Types-Type-visibleMemberships_Namespace_Boolean_Boolean-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-visibleMemberships_Namespace_Boolean_Boolean-isRecursive", name: "isRecursive", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-visibleMemberships_Namespace_Boolean_Boolean-includeAll", name: "includeAll", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Core-Types-Type-visibleMemberships_Namespace_Boolean_Boolean-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Kernel-Behaviors-ParameterMembership-parameterDirection_", declaring_metaclass: "ParameterMembership", name: "parameterDirection", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Behaviors-ParameterMembership-parameterDirection_-", name: "", target: "FeatureDirectionKind", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-ConstructorExpression-modelLevelEvaluable_Feature", declaring_metaclass: "ConstructorExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-ConstructorExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-ConstructorExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-FeatureChainExpression-sourceTargetFeature_", declaring_metaclass: "FeatureChainExpression", name: "sourceTargetFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-FeatureChainExpression-sourceTargetFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-FeatureReferenceExpression-evaluate_Element", declaring_metaclass: "FeatureReferenceExpression", name: "evaluate", redefines: &["Kernel-Functions-Expression-evaluate_Element"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-FeatureReferenceExpression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-FeatureReferenceExpression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Expressions-FeatureReferenceExpression-modelLevelEvaluable_Feature", declaring_metaclass: "FeatureReferenceExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-FeatureReferenceExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-FeatureReferenceExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-InstantiationExpression-instantiatedType_", declaring_metaclass: "InstantiationExpression", name: "instantiatedType", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-InstantiationExpression-instantiatedType_-", name: "", target: "Type", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-InvocationExpression-evaluate_Element", declaring_metaclass: "InvocationExpression", name: "evaluate", redefines: &["Kernel-Functions-Expression-evaluate_Element"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-InvocationExpression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-InvocationExpression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Expressions-InvocationExpression-modelLevelEvaluable_Feature", declaring_metaclass: "InvocationExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-InvocationExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-InvocationExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-LiteralExpression-evaluate_Element", declaring_metaclass: "LiteralExpression", name: "evaluate", redefines: &["Kernel-Functions-Expression-evaluate_Element"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-LiteralExpression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-LiteralExpression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Expressions-LiteralExpression-modelLevelEvaluable_Feature", declaring_metaclass: "LiteralExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-LiteralExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-LiteralExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-MetadataAccessExpression-evaluate_Element", declaring_metaclass: "MetadataAccessExpression", name: "evaluate", redefines: &["Kernel-Functions-Expression-evaluate_Element"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-MetadataAccessExpression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-MetadataAccessExpression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Expressions-MetadataAccessExpression-metaclassFeature_", declaring_metaclass: "MetadataAccessExpression", name: "metaclassFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-MetadataAccessExpression-metaclassFeature_-", name: "", target: "MetadataFeature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-MetadataAccessExpression-modelLevelEvaluable_Feature", declaring_metaclass: "MetadataAccessExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-MetadataAccessExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-MetadataAccessExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-NullExpression-evaluate_Element", declaring_metaclass: "NullExpression", name: "evaluate", redefines: &["Kernel-Functions-Expression-evaluate_Element"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-NullExpression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-NullExpression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Expressions-NullExpression-modelLevelEvaluable_Feature", declaring_metaclass: "NullExpression", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-NullExpression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Expressions-NullExpression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Expressions-OperatorExpression-instantiatedType_", declaring_metaclass: "OperatorExpression", name: "instantiatedType", redefines: &["Kernel-Expressions-InstantiationExpression-instantiatedType_"], parameters: &[
        ParameterSpec { id: "Kernel-Expressions-OperatorExpression-instantiatedType_-", name: "", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Functions-Expression-checkCondition_Element", declaring_metaclass: "Expression", name: "checkCondition", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Functions-Expression-checkCondition_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Functions-Expression-checkCondition_Element-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Functions-Expression-evaluate_Element", declaring_metaclass: "Expression", name: "evaluate", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Functions-Expression-evaluate_Element-target", name: "target", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Functions-Expression-evaluate_Element-result", name: "result", target: "Element", direction: None, lower: 0, upper: None, ordered: true, unique: false },
    ] },
    OperationSpec { id: "Kernel-Functions-Expression-modelLevelEvaluable_Feature", declaring_metaclass: "Expression", name: "modelLevelEvaluable", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Functions-Expression-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Functions-Expression-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Functions-ReturnParameterMembership-parameterDirection_", declaring_metaclass: "ReturnParameterMembership", name: "parameterDirection", redefines: &["Kernel-Behaviors-ParameterMembership-parameterDirection_"], parameters: &[
        ParameterSpec { id: "Kernel-Functions-ReturnParameterMembership-parameterDirection_-", name: "", target: "FeatureDirectionKind", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Metadata-MetadataFeature-evaluateFeature_Feature", declaring_metaclass: "MetadataFeature", name: "evaluateFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Metadata-MetadataFeature-evaluateFeature_Feature-baseFeature", name: "baseFeature", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Metadata-MetadataFeature-evaluateFeature_Feature-", name: "", target: "Element", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Metadata-MetadataFeature-isSemantic_", declaring_metaclass: "MetadataFeature", name: "isSemantic", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Metadata-MetadataFeature-isSemantic_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Metadata-MetadataFeature-isSyntactic_", declaring_metaclass: "MetadataFeature", name: "isSyntactic", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Metadata-MetadataFeature-isSyntactic_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Metadata-MetadataFeature-syntaxElement_", declaring_metaclass: "MetadataFeature", name: "syntaxElement", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Metadata-MetadataFeature-syntaxElement_-", name: "", target: "Element", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Multiplicities-MultiplicityRange-hasBounds_Integer_UnlimitedNatural", declaring_metaclass: "MultiplicityRange", name: "hasBounds", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Multiplicities-MultiplicityRange-hasBounds_Integer_UnlimitedNatural-lower", name: "lower", target: "Integer", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Multiplicities-MultiplicityRange-hasBounds_Integer_UnlimitedNatural-upper", name: "upper", target: "UnlimitedNatural", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Multiplicities-MultiplicityRange-hasBounds_Integer_UnlimitedNatural-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Multiplicities-MultiplicityRange-valueOf_Expression", declaring_metaclass: "MultiplicityRange", name: "valueOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Multiplicities-MultiplicityRange-valueOf_Expression-bound", name: "bound", target: "Expression", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Multiplicities-MultiplicityRange-valueOf_Expression-", name: "", target: "UnlimitedNatural", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Packages-LibraryPackage-libraryNamespace_", declaring_metaclass: "LibraryPackage", name: "libraryNamespace", redefines: &["Root-Elements-Element-libraryNamespace_"], parameters: &[
        ParameterSpec { id: "Kernel-Packages-LibraryPackage-libraryNamespace_-", name: "", target: "Namespace", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Packages-Package-importedMemberships_Namespace", declaring_metaclass: "Package", name: "importedMemberships", redefines: &["Root-Namespaces-Namespace-importedMemberships_Namespace"], parameters: &[
        ParameterSpec { id: "Kernel-Packages-Package-importedMemberships_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Packages-Package-importedMemberships_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Kernel-Packages-Package-includeAsMember_Element", declaring_metaclass: "Package", name: "includeAsMember", redefines: &[], parameters: &[
        ParameterSpec { id: "Kernel-Packages-Package-includeAsMember_Element-element", name: "element", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Kernel-Packages-Package-includeAsMember_Element-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Element-effectiveName_", declaring_metaclass: "Element", name: "effectiveName", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Elements-Element-effectiveName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Element-effectiveShortName_", declaring_metaclass: "Element", name: "effectiveShortName", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Elements-Element-effectiveShortName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Element-escapedName_", declaring_metaclass: "Element", name: "escapedName", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Elements-Element-escapedName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Element-libraryNamespace_", declaring_metaclass: "Element", name: "libraryNamespace", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Elements-Element-libraryNamespace_-", name: "", target: "Namespace", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Element-path_", declaring_metaclass: "Element", name: "path", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Elements-Element-path_-", name: "", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Relationship-libraryNamespace_", declaring_metaclass: "Relationship", name: "libraryNamespace", redefines: &["Root-Elements-Element-libraryNamespace_"], parameters: &[
        ParameterSpec { id: "Root-Elements-Relationship-libraryNamespace_-", name: "", target: "Namespace", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Elements-Relationship-path_", declaring_metaclass: "Relationship", name: "path", redefines: &["Root-Elements-Element-path_"], parameters: &[
        ParameterSpec { id: "Root-Elements-Relationship-path_-", name: "", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Import-importedMemberships_Namespace", declaring_metaclass: "Import", name: "importedMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Import-importedMemberships_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Import-importedMemberships_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Membership-isDistinguishableFrom_Membership", declaring_metaclass: "Membership", name: "isDistinguishableFrom", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Membership-isDistinguishableFrom_Membership-other", name: "other", target: "Membership", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Membership-isDistinguishableFrom_Membership-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-MembershipImport-importedMemberships_Namespace", declaring_metaclass: "MembershipImport", name: "importedMemberships", redefines: &["Root-Namespaces-Import-importedMemberships_Namespace"], parameters: &[
        ParameterSpec { id: "Root-Namespaces-MembershipImport-importedMemberships_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-MembershipImport-importedMemberships_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-importedMemberships_Namespace", declaring_metaclass: "Namespace", name: "importedMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-importedMemberships_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-importedMemberships_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-membershipsOfVisibility_VisibilityKind_Namespace", declaring_metaclass: "Namespace", name: "membershipsOfVisibility", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-membershipsOfVisibility_VisibilityKind_Namespace-visibility", name: "visibility", target: "VisibilityKind", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-membershipsOfVisibility_VisibilityKind_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-membershipsOfVisibility_VisibilityKind_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-namesOf_Element", declaring_metaclass: "Namespace", name: "namesOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-namesOf_Element-element", name: "element", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-namesOf_Element-", name: "", target: "String", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-qualificationOf_String", declaring_metaclass: "Namespace", name: "qualificationOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-qualificationOf_String-qualifiedName", name: "qualifiedName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-qualificationOf_String-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-resolveGlobal_String", declaring_metaclass: "Namespace", name: "resolveGlobal", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveGlobal_String-qualifiedName", name: "qualifiedName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveGlobal_String-", name: "", target: "Membership", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-resolveLocal_String", declaring_metaclass: "Namespace", name: "resolveLocal", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveLocal_String-name", name: "name", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveLocal_String-", name: "", target: "Membership", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-resolveVisible_String", declaring_metaclass: "Namespace", name: "resolveVisible", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveVisible_String-name", name: "name", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-resolveVisible_String-", name: "", target: "Membership", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-resolve_String", declaring_metaclass: "Namespace", name: "resolve", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-resolve_String-qualifiedName", name: "qualifiedName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-resolve_String-", name: "", target: "Membership", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-unqualifiedNameOf_String", declaring_metaclass: "Namespace", name: "unqualifiedNameOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-unqualifiedNameOf_String-qualifiedName", name: "qualifiedName", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-unqualifiedNameOf_String-", name: "", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-visibilityOf_Membership", declaring_metaclass: "Namespace", name: "visibilityOf", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-visibilityOf_Membership-mem", name: "mem", target: "Membership", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-visibilityOf_Membership-", name: "", target: "VisibilityKind", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean", declaring_metaclass: "Namespace", name: "visibleMemberships", redefines: &[], parameters: &[
        ParameterSpec { id: "Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean-isRecursive", name: "isRecursive", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean-includeAll", name: "includeAll", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-Namespace-visibleMemberships_Namespace_Boolean_Boolean-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-NamespaceImport-importedMemberships_Namespace", declaring_metaclass: "NamespaceImport", name: "importedMemberships", redefines: &["Root-Namespaces-Import-importedMemberships_Namespace"], parameters: &[
        ParameterSpec { id: "Root-Namespaces-NamespaceImport-importedMemberships_Namespace-excluded", name: "excluded", target: "Namespace", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Root-Namespaces-NamespaceImport-importedMemberships_Namespace-", name: "", target: "Membership", direction: None, lower: 0, upper: None, ordered: true, unique: true },
    ] },
    OperationSpec { id: "Root-Namespaces-OwningMembership-path_", declaring_metaclass: "OwningMembership", name: "path", redefines: &["Root-Elements-Relationship-path_"], parameters: &[
        ParameterSpec { id: "Root-Namespaces-OwningMembership-path_-", name: "", target: "String", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-AcceptActionUsage-isTriggerAction_", declaring_metaclass: "AcceptActionUsage", name: "isTriggerAction", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-AcceptActionUsage-isTriggerAction_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-ActionUsage-argument_Integer", declaring_metaclass: "ActionUsage", name: "argument", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-ActionUsage-argument_Integer-i", name: "i", target: "Integer", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Actions-ActionUsage-argument_Integer-", name: "", target: "Expression", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-ActionUsage-inputParameter_Integer", declaring_metaclass: "ActionUsage", name: "inputParameter", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-ActionUsage-inputParameter_Integer-i", name: "i", target: "Integer", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Actions-ActionUsage-inputParameter_Integer-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-ActionUsage-inputParameters_", declaring_metaclass: "ActionUsage", name: "inputParameters", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-ActionUsage-inputParameters_-", name: "", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-ActionUsage-isSubactionUsage_", declaring_metaclass: "ActionUsage", name: "isSubactionUsage", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-ActionUsage-isSubactionUsage_-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-ControlNode-multiplicityHasBounds_Multiplicity_Integer_UnlimitedNatural", declaring_metaclass: "ControlNode", name: "multiplicityHasBounds", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Actions-ControlNode-multiplicityHasBounds_Multiplicity_Integer_UnlimitedNatural-mult", name: "mult", target: "Multiplicity", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Actions-ControlNode-multiplicityHasBounds_Multiplicity_Integer_UnlimitedNatural-lower", name: "lower", target: "Integer", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Actions-ControlNode-multiplicityHasBounds_Multiplicity_Integer_UnlimitedNatural-upper", name: "upper", target: "UnlimitedNatural", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Actions-ControlNode-multiplicityHasBounds_Multiplicity_Integer_UnlimitedNatural-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-PerformActionUsage-namingFeature_", declaring_metaclass: "PerformActionUsage", name: "namingFeature", redefines: &["Systems-DefinitionAndUsage-Usage-namingFeature_"], parameters: &[
        ParameterSpec { id: "Systems-Actions-PerformActionUsage-namingFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Actions-TriggerInvocationExpression-instantiatedType_", declaring_metaclass: "TriggerInvocationExpression", name: "instantiatedType", redefines: &["Kernel-Expressions-InstantiationExpression-instantiatedType_"], parameters: &[
        ParameterSpec { id: "Systems-Actions-TriggerInvocationExpression-instantiatedType_-", name: "", target: "Type", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Calculations-CalculationUsage-modelLevelEvaluable_Feature", declaring_metaclass: "CalculationUsage", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Systems-Calculations-CalculationUsage-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Systems-Calculations-CalculationUsage-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Constraints-ConstraintUsage-modelLevelEvaluable_Feature", declaring_metaclass: "ConstraintUsage", name: "modelLevelEvaluable", redefines: &["Kernel-Functions-Expression-modelLevelEvaluable_Feature"], parameters: &[
        ParameterSpec { id: "Systems-Constraints-ConstraintUsage-modelLevelEvaluable_Feature-visited", name: "visited", target: "Feature", direction: None, lower: 0, upper: None, ordered: false, unique: true },
        ParameterSpec { id: "Systems-Constraints-ConstraintUsage-modelLevelEvaluable_Feature-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Constraints-ConstraintUsage-namingFeature_", declaring_metaclass: "ConstraintUsage", name: "namingFeature", redefines: &["Systems-DefinitionAndUsage-Usage-namingFeature_"], parameters: &[
        ParameterSpec { id: "Systems-Constraints-ConstraintUsage-namingFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-DefinitionAndUsage-ReferenceUsage-namingFeature_", declaring_metaclass: "ReferenceUsage", name: "namingFeature", redefines: &["Systems-DefinitionAndUsage-Usage-namingFeature_"], parameters: &[
        ParameterSpec { id: "Systems-DefinitionAndUsage-ReferenceUsage-namingFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-DefinitionAndUsage-Usage-namingFeature_", declaring_metaclass: "Usage", name: "namingFeature", redefines: &["Core-Features-Feature-namingFeature_"], parameters: &[
        ParameterSpec { id: "Systems-DefinitionAndUsage-Usage-namingFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-DefinitionAndUsage-Usage-referencedFeatureTarget_", declaring_metaclass: "Usage", name: "referencedFeatureTarget", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-DefinitionAndUsage-Usage-referencedFeatureTarget_-", name: "", target: "Feature", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Ports-ConjugatedPortDefinition-effectiveName_", declaring_metaclass: "ConjugatedPortDefinition", name: "effectiveName", redefines: &["Root-Elements-Element-effectiveName_"], parameters: &[
        ParameterSpec { id: "Systems-Ports-ConjugatedPortDefinition-effectiveName_-", name: "", target: "String", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-States-StateUsage-isSubstateUsage_Boolean", declaring_metaclass: "StateUsage", name: "isSubstateUsage", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-States-StateUsage-isSubstateUsage_Boolean-isParallel", name: "isParallel", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-States-StateUsage-isSubstateUsage_Boolean-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-States-TransitionUsage-sourceFeature_", declaring_metaclass: "TransitionUsage", name: "sourceFeature", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-States-TransitionUsage-sourceFeature_-", name: "", target: "Feature", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-States-TransitionUsage-triggerPayloadParameter_", declaring_metaclass: "TransitionUsage", name: "triggerPayloadParameter", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-States-TransitionUsage-triggerPayloadParameter_-", name: "", target: "ReferenceUsage", direction: None, lower: 0, upper: Some(1), ordered: false, unique: true },
    ] },
    OperationSpec { id: "Systems-Views-ViewUsage-includeAsExposed_Element", declaring_metaclass: "ViewUsage", name: "includeAsExposed", redefines: &[], parameters: &[
        ParameterSpec { id: "Systems-Views-ViewUsage-includeAsExposed_Element-element", name: "element", target: "Element", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
        ParameterSpec { id: "Systems-Views-ViewUsage-includeAsExposed_Element-", name: "", target: "Boolean", direction: None, lower: 1, upper: Some(1), ordered: false, unique: true },
    ] },
];
