#!/usr/bin/env python3
"""Generate an operation declaration inventory, without inferring XMI signatures."""
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = "{http://www.omg.org/spec/XMI/20161101}"
OUT = ROOT / "crates/sysmlv2-model/src/operation_catalog.rs"


def ref(e):
    return e.get(NS + "idref", e.get("href", "").split("#")[-1])


def generate():
    roots = [ET.parse(ROOT / f"spec-refs/{name}.xmi").getroot() for name in ("KerML", "SysML")]
    ids = {e.get(NS + "id"): e for root in roots for e in root.iter() if e.get(NS + "id")}
    operations = sorted((op.get(NS + "id"), c, op) for c in ids.values()
                        if c.get(NS + "type") == "uml:Class" for op in c.findall("ownedOperation"))
    lines = [
        '//! Generated by `tools/operation_catalog.py` from the normative 20250201 XMI.',
        '//! Declaration metadata only; no executable support is implied.',
        '',
        '#[derive(Debug)]',
        'pub struct ParameterSpec {',
        "    pub id: &'static str,",
        "    pub name: &'static str,",
        "    pub target: &'static str,",
        '    /// The explicit XMI direction, or None if omitted. No return role is inferred.',
        "    pub direction: Option<&'static str>,",
        '    pub lower: usize,',
        '    pub upper: Option<usize>,',
        '    pub ordered: bool,',
        '    pub unique: bool,',
        '}',
        '',
        '#[derive(Debug)]',
        'pub struct OperationSpec {',
        "    pub id: &'static str,",
        "    pub declaring_metaclass: &'static str,",
        "    pub name: &'static str,",
        "    pub redefines: &'static [&'static str],",
        '    /// Source declaration order, including unnamed parameters.',
        "    pub parameters: &'static [ParameterSpec],",
        '}',
        '',
        '#[rustfmt::skip]',
        'pub static OPERATIONS: &[OperationSpec] = &[',
    ]
    for oid, owner, op in operations:
        redefines = [ref(r) for r in op.findall('redefinedOperation')]
        lines.append('    OperationSpec { id: %s, declaring_metaclass: %s, name: %s, redefines: &%s, parameters: &[' % (
            json.dumps(oid), json.dumps(owner.get('name')), json.dumps(op.get('name')), json.dumps(redefines)))
        for p in op.findall('ownedParameter'):
            target = ref(p.find('type')) if p.find('type') is not None else p.get('type', '')
            if target in ids:
                target = ids[target].get('name')
            lo, hi = p.find('lowerValue'), p.find('upperValue')
            lower = int(lo.get('value', '0')) if lo is not None else 1
            upper = hi.get('value', '0') if hi is not None else '1'
            direction = f"Some({json.dumps(p.get('direction'))})" if 'direction' in p.attrib else 'None'
            lines.append('        ParameterSpec { id: %s, name: %s, target: %s, direction: %s, lower: %s, upper: %s, ordered: %s, unique: %s },' % (
                json.dumps(p.get(NS + 'id')), json.dumps(p.get('name', '')), json.dumps(target), direction,
                lower, 'None' if upper in ('-1', '*') else f'Some({upper})',
                str(p.get('isOrdered', 'false') == 'true').lower(), str(p.get('isUnique', 'true') == 'true').lower()))
        lines.append('    ] },')
    lines += ['];', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    content = generate()
    if '--check' in sys.argv:
        if OUT.read_text() != content:
            raise SystemExit('operation catalog is stale; run python3 tools/operation_catalog.py')
    else:
        OUT.write_text(content)
