#!/usr/bin/env python3
"""Generate semantic property dispatch from the normative KerML/SysML XMI.

Redefinitions retain the inherited spelling as an alias of the most specific
property. Runtime lookup uses sorted tables, without loading XML or scanning
the entire metamodel. Run with --check to verify committed output.
"""
import json
import sys
import xml.etree.ElementTree as ET
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = "{http://www.omg.org/spec/XMI/20161101}"
OUT = ROOT / "crates/sysmlv2-model/src/semantic_catalog.rs"


def ref(e):
    return e.get(NS + "idref", e.get("href", "").split("#")[-1])


def generate():
    roots = [ET.parse(ROOT / f"spec-refs/{name}.xmi").getroot() for name in ("KerML", "SysML")]
    ids = {e.get(NS + "id"): e for r in roots for e in r.iter() if e.get(NS + "id")}
    classes = {i: e for i, e in ids.items() if e.get(NS + "type") == "uml:Class"}
    props = {p.get(NS + "id"): (i, p) for i, c in classes.items() for p in c.findall("ownedAttribute")}
    keys = sorted(props)
    indices = {p: i for i, p in enumerate(keys)}

    @lru_cache(None)
    def ancestors(i):
        return frozenset([i]).union(*(ancestors(ref(g)) for g in classes[i].findall("generalization/general")))

    @lru_cache(None)
    def redefines(i):
        return frozenset([i]).union(*(redefines(ref(r)) for r in props[i][1].findall("redefinedProperty")))

    def default(p):
        d = p.find("defaultValue")
        if d is None:
            return "None"
        kind = d.get(NS + "type", "")
        value = d.get("value")
        if kind == "uml:LiteralBoolean":
            v = value == "true"
        elif kind in ("uml:LiteralInteger", "uml:LiteralUnlimitedNatural"):
            v = int(value or 0)
        elif kind == "uml:LiteralString":
            v = value or ""
        elif kind == "uml:InstanceValue" and d.find("instance") is not None:
            v = ids[ref(d.find("instance"))].get("name")
        else:
            raise ValueError(f"unsupported default: {ET.tostring(d)}")
        return f"Some({json.dumps(json.dumps(v, separators=(',', ':')))})"

    lines = [
        '//! Generated by `tools/semantic_catalog.py` from the normative 20250201 XMI.',
        '//! Do not edit; regenerate or use `--check`.',
        '',
        '#[derive(Debug)]',
        'pub struct PropertySpec {',
        "    pub id: &'static str,",
        "    pub declaring_metaclass: &'static str,",
        "    pub name: &'static str,",
        "    pub target: &'static str,",
        '    pub derived: bool,',
        '    pub lower: usize,',
        '    pub unique: bool,',
        '    pub ordered: bool,',
        "    pub enum_values: &'static [&'static str],",
        '    pub upper: Option<usize>,',
        "    pub default_json: Option<&'static str>,",
        "    pub storage_names: &'static [&'static str],",
        '}',
        '',
        '#[rustfmt::skip]',
        'pub static PROPERTIES: &[PropertySpec] = &[',
    ]
    for i in keys:
        owner, p = props[i]
        target = ref(p.find("type")) if p.find("type") is not None else p.get("type", "")
        enum_values = [e.get("name") for e in ids[target].findall("ownedLiteral")] if target in ids else []
        target = ids[target].get("name") if target in ids else target
        lo, hi = p.find("lowerValue"), p.find("upperValue")
        lower = int(lo.get("value", "0")) if lo is not None else 1
        upper = hi.get("value", "0") if hi is not None else "1"
        names = [p.get("name")] + sorted({props[x][1].get("name") for x in redefines(i)} - {p.get("name")})
        lines.append('    PropertySpec { id: %s, declaring_metaclass: %s, name: %s, target: %s, derived: %s, lower: %s, upper: %s, default_json: %s, storage_names: &%s, unique: %s, ordered: %s, enum_values: &%s },' % (
            json.dumps(i), json.dumps(classes[owner].get("name")), json.dumps(p.get("name")), json.dumps(target), str(p.get("isDerived") == "true").lower(), lower,
            "None" if upper in ("-1", "*") else f"Some({upper})", default(p), json.dumps(names), str(p.get("isUnique", "true") == "true").lower(), str(p.get("isOrdered", "false") == "true").lower(), json.dumps(enum_values)))
    # A row's key is its requested declaration's own name, so rows hold
    # indices only: a string reference per row would be most of the table's
    # bytes, repeating what PROPERTIES already holds.
    lines += ['];', '',
              '/// One visible property of a metaclass: the `PROPERTIES` index of the',
              '/// declaration its name resolves to, then of the most specific',
              '/// redefinition (`u16::MAX` when redefinitions are incomparable). Rows',
              '/// sort by the requested declaration\'s name, which is their lookup key.',
              'pub type PropertyRow = (u16, u16);',
              "pub type ClassProperties = (&'static str, &'static [PropertyRow]);", '#[rustfmt::skip]', 'pub static CLASSES: &[ClassProperties] = &[']
    for cid, c in sorted(classes.items(), key=lambda x: x[1].get("name")):
        inherited = {p for p, (owner, _) in props.items() if owner in ancestors(cid)}
        rows = {}
        for pid in sorted(inherited):
            name = props[pid][1].get("name")
            candidates = {p for p in inherited if pid in redefines(p)}
            nearest = [p for p in candidates if not any(p != q and (p in redefines(q) or props[p][0] != props[q][0] and props[p][0] in ancestors(props[q][0])) for q in candidates)]
            # If a name appears independently through multiple inheritance,
            # a declaration on a subclass wins; incomparable declarations must
            # agree rather than silently choosing one by file order.
            winner = nearest[0] if len(nearest) == 1 else None
            if name in rows:
                old, _ = rows[name]
                if props[old][0] in ancestors(props[pid][0]):
                    rows[name] = (pid, winner)
                elif props[pid][0] not in ancestors(props[old][0]):
                    raise ValueError(f"ambiguous inherited property: {c.get('name')}.{name}")
            else:
                rows[name] = (pid, winner)
        lines.append(f'    ({json.dumps(c.get("name"))}, &[')
        for name, (p, w) in sorted(rows.items()):
            assert props[p][1].get("name") == name, (c.get("name"), name)
            lines.append(f'        ({indices[p]}, {indices[w] if w else 65535}), // {name}')
        lines.append('    ]),')
    lines += ['];', '', '#[rustfmt::skip]', 'pub fn properties(metaclass: &str) -> Option<&\'static [PropertyRow]> {',
              '    CLASSES.binary_search_by_key(&metaclass, |(name, _)| *name).ok().map(|i| CLASSES[i].1)', '}', '',
              '#[rustfmt::skip]', 'pub fn property(metaclass: &str, name: &str) -> Option<(&\'static PropertySpec, Option<&\'static PropertySpec>)> {',
              '    let props = properties(metaclass)?;',
              '    props.binary_search_by_key(&name, |&(requested, _)| PROPERTIES[requested as usize].name).ok().map(|i| (&PROPERTIES[props[i].0 as usize], PROPERTIES.get(props[i].1 as usize)))', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    content = generate()
    if '--check' in sys.argv:
        if OUT.read_text() != content:
            raise SystemExit('semantic catalog is stale; run python3 tools/semantic_catalog.py')
    else:
        OUT.write_text(content)
